#pragma once

void test_stack_constructor();
void test_stack_push();
void test_stack_pop();
void test_array_sequence_resize();
void test_list_sequence_resize();
void test_stack_peek();
void test_stack_is_empty();
void test_stack_get_size();
void test_stack_operators();
void test_queue_constructor();
void test_queue_enqueue();
void test_queue_dequeue();
void test_queue_front_back();
void test_queue_empty_and_size();
void test_queue_operators();
void test_stack_exceptions();
void test_queue_exceptions();
void test_deque_push_front();
void test_deque_push_back();
void test_deque_pop_front();
void test_deque_pop_back();
void test_deque_front_back();
void test_deque_empty_and_size();
void test_deque_exceptions();
void test_deque_operators();